### PR TITLE
Rov 174 arrange boxes on account s home screen in one horizontal row

### PR DESCRIPTION
**Pull request by Varuno8**

### CODE REVIEW

**Comment by Vedant-Tyagi** [comment]
I have reviewed and I found no mistake.

**Comment by yanshityagi** [comment]
@Vedant-Tyagi Please also add a screenshot of how the screen looks on your device.

**Comment by yaneshtyagi** [comment]
@Vedant-Tyagi it's been  3 weeks since Yanshi asked for the screenshot. Are you too busy, too ignorant, or just don't know how to add screenshot.

**Comment by Vedant-Tyagi** [comment]
image

This is how it is looking on my screen 
@yaneshtyagi  I had seen Yanshi in the meeting to see how he was looking.

**Pull request closed without merging**
