### PR TITLE
Rov 196 develop loan amortization calculator

### PR DESCRIPTION
**Pull request by Varuno8**

### CODE REVIEW

**Review by Vedant-Tyagi — APPROVED** [review]
The card functionality is working fine

**Comment by yaneshtyagi** [comment]
@Varuno8 Please resolve conflicts.

**Review by yaneshtyagi — CHANGES_REQUESTED** [review]
Please resolve the conflicts.

**Review by Vedant-Tyagi — DISMISSED** [review]

**Comment by Vedant-Tyagi** [comment]
@yaneshtyagi I have reviewed the card now all conflict has been resolved

**Review by yaneshtyagi — DISMISSED** [review]

**Review by Vedant-Tyagi — APPROVED** [review]
The card functionality is working fine

**Review by Vedant-Tyagi — APPROVED** [review]
The card functionality is working fine and all the conflict has resolved

**Pull request merged**
